variables:
  GIT_DEPTH: "1"
  OPAMYES: "true"

image: ocaml/opam2:alpine-3.10-opam

cache:
  key: "alpine-key"
  paths:
    - _opam

before_script:
  - opam init --bare
  - '[ ! -d "_opam" ] && opam switch create . 4.09.0 --no-install'
  - opam install fmt
  - opam pin add async-http.dev -n .
  - opam depext async-http
  - opam install -t . --deps-only

build:
  stage: build
  script:
    - opam exec -- dune build
  only:
    - master

test:
  stage: test
  script:
    - opam exec -- dune build
    - opam exec -- dune runtest
  only:
    - merge_request
