variables:
  GIT_DEPTH: "1"
  OPAMYES: "true"

image: ubuntu:19.10

cache:
  paths:
    - _opam

before_script:
  - apt update
  - apt install -y opam
  - opam init --bare
  - opam switch create . 4.09.0 --no-install
  - eval $(opam env)
  - echo ocaml --version
  - opam pin add async-http.dev -n .
  - opam depext async-http
  - opam install -t . --deps-only

build:
  stage: build
  script:
    - opam exec -- dune build

test:
  stage: test
  script:
    - opam exec -- dune runtest
