variables:
  GIT_DEPTH: "1"

image: ubuntu:19.10

cache:
  key: esy-cache
  paths:
    - ~/.esy/3____________________________________________________________________/i/

before_script:
  - apt update
  - apt install -y nodejs npm m4 patch
  - mkdir ~/.npm-global
  - npm config set prefix '~/.npm-global'
  - npm install -g esy@0.6.2 --unsafe-perm=true
  - ~/.npm-global/bin/esy fetch

build:
  stage: build
  script:
    - ~/.npm-global/bin/esy build
    - ~/.npm-global/bin/esy dune build @examples

test:
  stage: test
  script:
    - ~/.npm-global/bin/esy dune runtest
